### ISSUE TITLE
Add no_application_protocol alert.

### ISSUE THREAD

**Issue by seanturner** [seanturner/draft-sandj-tls-iana-registry-updates#10]
Hubert Kario noted:

The IANA [TLS Alert Registry](https://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml#tls-parameters-6) does not include the 
no_application_protocol(120) alert from [RFC7301](https://tools.ietf.org/html/rfc7301#section-3.2) (a.k.a. Application-Layer 
Protocol Negotiation Extension)

**Comment by jsalowey** [comment]
Opened PR #11 to add alert to registry.

**Comment by jsalowey** [comment]
I guess we should close when the PR is merged.
